namespace Launcher.Forms
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up used resources.
        /// </summary>
        /// <param name="disposing">True if managed resources are to be deleted; otherwise, False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Windows Form Designer

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.LoginGroupBox = new System.Windows.Forms.GroupBox();
            this.hideBrowserFormCheckBox = new System.Windows.Forms.CheckBox();
            this.affinityBitmaskTextBox = new System.Windows.Forms.TextBox();
            this.coreAffinityCheckBox = new System.Windows.Forms.CheckBox();
            this.adminCheckBox = new System.Windows.Forms.CheckBox();
            this.MacAddressTextBox = new System.Windows.Forms.TextBox();
            this.pcRegCheckBox = new System.Windows.Forms.CheckBox();
            this.usernameTextBox = new System.Windows.Forms.TextBox();
            this.usernameLabel = new System.Windows.Forms.Label();
            this.passwordLabel = new System.Windows.Forms.Label();
            this.passwordTextBox = new System.Windows.Forms.TextBox();
            this.otpCheckBox = new System.Windows.Forms.CheckBox();
            this.otpTextBox = new System.Windows.Forms.TextBox();
            this.regionLabel = new System.Windows.Forms.Label();
            this.regionComboBox = new System.Windows.Forms.ComboBox();
            this.gameMode32BitCheckBox = new System.Windows.Forms.CheckBox();
            this.rememberDataCheckBox = new System.Windows.Forms.CheckBox();
            this.loginAutomaticallyCheckBox = new System.Windows.Forms.CheckBox();
            this.launcherUpdateCheckBox = new System.Windows.Forms.CheckBox();
            this.gameUpdateCheckBox = new System.Windows.Forms.CheckBox();
            this.startGameBtn = new System.Windows.Forms.Button();
            this.gameDirectoryPathLinkLabel = new System.Windows.Forms.LinkLabel();
            this.githubLinkLabel = new System.Windows.Forms.LinkLabel();
            this.LoginGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // LoginGroupBox
            // 
            this.LoginGroupBox.Controls.Add(this.hideBrowserFormCheckBox);
            this.LoginGroupBox.Controls.Add(this.affinityBitmaskTextBox);
            this.LoginGroupBox.Controls.Add(this.coreAffinityCheckBox);
            this.LoginGroupBox.Controls.Add(this.adminCheckBox);
            this.LoginGroupBox.Controls.Add(this.MacAddressTextBox);
            this.LoginGroupBox.Controls.Add(this.pcRegCheckBox);
            this.LoginGroupBox.Controls.Add(this.usernameTextBox);
            this.LoginGroupBox.Controls.Add(this.usernameLabel);
            this.LoginGroupBox.Controls.Add(this.passwordLabel);
            this.LoginGroupBox.Controls.Add(this.passwordTextBox);
            this.LoginGroupBox.Controls.Add(this.otpCheckBox);
            this.LoginGroupBox.Controls.Add(this.otpTextBox);
            this.LoginGroupBox.Controls.Add(this.regionLabel);
            this.LoginGroupBox.Controls.Add(this.regionComboBox);
            this.LoginGroupBox.Controls.Add(this.gameMode32BitCheckBox);
            this.LoginGroupBox.Controls.Add(this.rememberDataCheckBox);
            this.LoginGroupBox.Controls.Add(this.loginAutomaticallyCheckBox);
            this.LoginGroupBox.Controls.Add(this.launcherUpdateCheckBox);
            this.LoginGroupBox.Controls.Add(this.gameUpdateCheckBox);
            this.LoginGroupBox.Controls.Add(this.startGameBtn);
            this.LoginGroupBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LoginGroupBox.Location = new System.Drawing.Point(12, 12);
            this.LoginGroupBox.Name = "LoginGroupBox";
            this.LoginGroupBox.Size = new System.Drawing.Size(337, 284);
            this.LoginGroupBox.TabIndex = 1;
            this.LoginGroupBox.TabStop = false;
            this.LoginGroupBox.Text = "Login";
            // 
            // hideBrowserFormCheckBox
            // 
            this.hideBrowserFormCheckBox.Location = new System.Drawing.Point(188, 222);
            this.hideBrowserFormCheckBox.Name = "hideBrowserFormCheckBox";
            this.hideBrowserFormCheckBox.Size = new System.Drawing.Size(126, 24);
            this.hideBrowserFormCheckBox.TabIndex = 18;
            this.hideBrowserFormCheckBox.Text = "Hide BrowserForm";
            this.hideBrowserFormCheckBox.CheckedChanged += new System.EventHandler(this.HideBrowserFormCheckBox_CheckedChanged);
            // 
            // affinityBitmaskTextBox
            // 
            this.affinityBitmaskTextBox.Location = new System.Drawing.Point(128, 137);
            this.affinityBitmaskTextBox.Name = "affinityBitmaskTextBox";
            this.affinityBitmaskTextBox.Size = new System.Drawing.Size(190, 22);
            this.affinityBitmaskTextBox.TabIndex = 17;
            // 
            // coreAffinityCheckBox
            // 
            this.coreAffinityCheckBox.Location = new System.Drawing.Point(16, 135);
            this.coreAffinityCheckBox.Name = "coreAffinityCheckBox";
            this.coreAffinityCheckBox.Size = new System.Drawing.Size(107, 24);
            this.coreAffinityCheckBox.TabIndex = 16;
            this.coreAffinityCheckBox.Text = "Core Affinity";
            this.coreAffinityCheckBox.UseVisualStyleBackColor = true;
            this.coreAffinityCheckBox.CheckedChanged += new System.EventHandler(this.CoreAffinityCheckBox_CheckedChanged);
            // 
            // adminCheckBox
            // 
            this.adminCheckBox.Location = new System.Drawing.Point(16, 222);
            this.adminCheckBox.Name = "adminCheckBox";
            this.adminCheckBox.Size = new System.Drawing.Size(141, 24);
            this.adminCheckBox.TabIndex = 0;
            this.adminCheckBox.Text = "Launch As Admin";
            this.adminCheckBox.CheckedChanged += new System.EventHandler(this.adminCheckBox_CheckedChanged);
            // 
            // MacAddressTextBox
            // 
            this.MacAddressTextBox.Location = new System.Drawing.Point(129, 107);
            this.MacAddressTextBox.Name = "MacAddressTextBox";
            this.MacAddressTextBox.Size = new System.Drawing.Size(190, 22);
            this.MacAddressTextBox.TabIndex = 15;
            // 
            // pcRegCheckBox
            // 
            this.pcRegCheckBox.Location = new System.Drawing.Point(16, 105);
            this.pcRegCheckBox.Name = "pcRegCheckBox";
            this.pcRegCheckBox.Size = new System.Drawing.Size(107, 24);
            this.pcRegCheckBox.TabIndex = 14;
            this.pcRegCheckBox.Text = "PC Registration";
            this.pcRegCheckBox.UseVisualStyleBackColor = true;
            this.pcRegCheckBox.CheckedChanged += new System.EventHandler(this.MacAddressCheckBox_CheckedChanged);
            // 
            // usernameTextBox
            // 
            this.usernameTextBox.Location = new System.Drawing.Point(83, 21);
            this.usernameTextBox.Name = "usernameTextBox";
            this.usernameTextBox.Size = new System.Drawing.Size(236, 22);
            this.usernameTextBox.TabIndex = 1;
            // 
            // usernameLabel
            // 
            this.usernameLabel.AutoSize = true;
            this.usernameLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.usernameLabel.Location = new System.Drawing.Point(16, 24);
            this.usernameLabel.Name = "usernameLabel";
            this.usernameLabel.Size = new System.Drawing.Size(58, 13);
            this.usernameLabel.TabIndex = 0;
            this.usernameLabel.Text = "Username";
            // 
            // passwordLabel
            // 
            this.passwordLabel.AutoSize = true;
            this.passwordLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.passwordLabel.Location = new System.Drawing.Point(16, 52);
            this.passwordLabel.Name = "passwordLabel";
            this.passwordLabel.Size = new System.Drawing.Size(56, 13);
            this.passwordLabel.TabIndex = 2;
            this.passwordLabel.Text = "Password";
            // 
            // passwordTextBox
            // 
            this.passwordTextBox.Location = new System.Drawing.Point(83, 49);
            this.passwordTextBox.Name = "passwordTextBox";
            this.passwordTextBox.PasswordChar = '*';
            this.passwordTextBox.Size = new System.Drawing.Size(236, 22);
            this.passwordTextBox.TabIndex = 3;
            // 
            // otpCheckBox
            // 
            this.otpCheckBox.Location = new System.Drawing.Point(16, 79);
            this.otpCheckBox.Name = "otpCheckBox";
            this.otpCheckBox.Size = new System.Drawing.Size(56, 17);
            this.otpCheckBox.TabIndex = 4;
            this.otpCheckBox.Text = "OTP";
            this.otpCheckBox.UseVisualStyleBackColor = true;
            this.otpCheckBox.CheckedChanged += new System.EventHandler(this.OtpCheckBox_CheckedChanged);
            // 
            // otpTextBox
            // 
            this.otpTextBox.Location = new System.Drawing.Point(83, 77);
            this.otpTextBox.Name = "otpTextBox";
            this.otpTextBox.PasswordChar = '*';
            this.otpTextBox.Size = new System.Drawing.Size(107, 22);
            this.otpTextBox.TabIndex = 5;
            // 
            // regionLabel
            // 
            this.regionLabel.Location = new System.Drawing.Point(193, 80);
            this.regionLabel.Name = "regionLabel";
            this.regionLabel.Size = new System.Drawing.Size(48, 21);
            this.regionLabel.TabIndex = 6;
            this.regionLabel.Text = "Region";
            // 
            // regionComboBox
            // 
            this.regionComboBox.AutoCompleteCustomSource.AddRange(new string[] { "NA", "EU" });
            this.regionComboBox.FormattingEnabled = true;
            this.regionComboBox.Items.AddRange(new object[] { "NA", "EU" });
            this.regionComboBox.Location = new System.Drawing.Point(247, 77);
            this.regionComboBox.MaxDropDownItems = 2;
            this.regionComboBox.Name = "regionComboBox";
            this.regionComboBox.Size = new System.Drawing.Size(71, 21);
            this.regionComboBox.TabIndex = 7;
            this.regionComboBox.SelectedIndexChanged += new System.EventHandler(this.RegionComboBox_SelectedIndexChanged);
            // 
            // gameMode32BitCheckBox
            // 
            this.gameMode32BitCheckBox.Location = new System.Drawing.Point(16, 165);
            this.gameMode32BitCheckBox.Name = "gameMode32BitCheckBox";
            this.gameMode32BitCheckBox.Size = new System.Drawing.Size(56, 24);
            this.gameMode32BitCheckBox.TabIndex = 8;
            this.gameMode32BitCheckBox.Text = "32 BIT";
            this.gameMode32BitCheckBox.UseVisualStyleBackColor = true;
            this.gameMode32BitCheckBox.CheckedChanged += new System.EventHandler(this.GameModeCheckBox_CheckedChanged);
            // 
            // rememberDataCheckBox
            // 
            this.rememberDataCheckBox.AutoSize = true;
            this.rememberDataCheckBox.Location = new System.Drawing.Point(80, 169);
            this.rememberDataCheckBox.Name = "rememberDataCheckBox";
            this.rememberDataCheckBox.Size = new System.Drawing.Size(107, 17);
            this.rememberDataCheckBox.TabIndex = 9;
            this.rememberDataCheckBox.Text = "Remember Data";
            this.rememberDataCheckBox.UseVisualStyleBackColor = true;
            this.rememberDataCheckBox.CheckedChanged += new System.EventHandler(this.RememberDataCheckBox_CheckedChanged);
            // 
            // loginAutomaticallyCheckBox
            // 
            this.loginAutomaticallyCheckBox.AutoSize = true;
            this.loginAutomaticallyCheckBox.Location = new System.Drawing.Point(188, 169);
            this.loginAutomaticallyCheckBox.Name = "loginAutomaticallyCheckBox";
            this.loginAutomaticallyCheckBox.Size = new System.Drawing.Size(126, 17);
            this.loginAutomaticallyCheckBox.TabIndex = 10;
            this.loginAutomaticallyCheckBox.Text = "Login automatically";
            this.loginAutomaticallyCheckBox.UseVisualStyleBackColor = true;
            this.loginAutomaticallyCheckBox.CheckedChanged += new System.EventHandler(this.LoginAutomaticallyCheckBox_CheckedChanged);
            // 
            // launcherUpdateCheckBox
            // 
            this.launcherUpdateCheckBox.Location = new System.Drawing.Point(16, 192);
            this.launcherUpdateCheckBox.Name = "launcherUpdateCheckBox";
            this.launcherUpdateCheckBox.Size = new System.Drawing.Size(152, 24);
            this.launcherUpdateCheckBox.TabIndex = 12;
            this.launcherUpdateCheckBox.Text = "Check Launcher Update";
            this.launcherUpdateCheckBox.UseVisualStyleBackColor = true;
            this.launcherUpdateCheckBox.CheckedChanged += new System.EventHandler(this.launcherUpdate_CheckedChanged);
            // 
            // gameUpdateCheckBox
            // 
            this.gameUpdateCheckBox.Location = new System.Drawing.Point(188, 192);
            this.gameUpdateCheckBox.Name = "gameUpdateCheckBox";
            this.gameUpdateCheckBox.Size = new System.Drawing.Size(130, 24);
            this.gameUpdateCheckBox.TabIndex = 13;
            this.gameUpdateCheckBox.Text = "Check Game Update";
            this.gameUpdateCheckBox.UseVisualStyleBackColor = true;
            this.gameUpdateCheckBox.CheckedChanged += new System.EventHandler(this.gameUpdateCheckBox_CheckedChanged);
            // 
            // startGameBtn
            // 
            this.startGameBtn.Location = new System.Drawing.Point(16, 252);
            this.startGameBtn.Name = "startGameBtn";
            this.startGameBtn.Size = new System.Drawing.Size(302, 23);
            this.startGameBtn.TabIndex = 11;
            this.startGameBtn.Text = "Start Game";
            this.startGameBtn.UseVisualStyleBackColor = true;
            this.startGameBtn.Click += new System.EventHandler(this.StartGameButton_Click);
            // 
            // gameDirectoryPathLinkLabel
            // 
            this.gameDirectoryPathLinkLabel.AutoSize = true;
            this.gameDirectoryPathLinkLabel.Location = new System.Drawing.Point(12, 299);
            this.gameDirectoryPathLinkLabel.Name = "gameDirectoryPathLinkLabel";
            this.gameDirectoryPathLinkLabel.Size = new System.Drawing.Size(81, 13);
            this.gameDirectoryPathLinkLabel.TabIndex = 12;
            this.gameDirectoryPathLinkLabel.TabStop = true;
            this.gameDirectoryPathLinkLabel.Text = "Set Game Path";
            this.gameDirectoryPathLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.GameDirectoryPathLinkLabel_LinkClicked);
            // 
            // githubLinkLabel
            // 
            this.githubLinkLabel.AutoSize = true;
            this.githubLinkLabel.Location = new System.Drawing.Point(209, 299);
            this.githubLinkLabel.Name = "githubLinkLabel";
            this.githubLinkLabel.Size = new System.Drawing.Size(140, 13);
            this.githubLinkLabel.TabIndex = 13;
            this.githubLinkLabel.TabStop = true;
            this.githubLinkLabel.Text = "Report An Issue (Click Me)";
            this.githubLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.GithubLinkLabel_LinkClicked);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(364, 321);
            this.Controls.Add(this.gameDirectoryPathLinkLabel);
            this.Controls.Add(this.githubLinkLabel);
            this.Controls.Add(this.LoginGroupBox);
            this.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MainForm";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.LoginGroupBox.ResumeLayout(false);
            this.LoginGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.CheckBox hideBrowserFormCheckBox;

        private System.Windows.Forms.TextBox affinityBitmaskTextBox;

        private System.Windows.Forms.CheckBox coreAffinityCheckBox;

        #endregion

        private System.Windows.Forms.GroupBox LoginGroupBox;
        private System.Windows.Forms.Label usernameLabel;
        private System.Windows.Forms.TextBox usernameTextBox;
        private System.Windows.Forms.Label passwordLabel;
        private System.Windows.Forms.TextBox passwordTextBox;
        private System.Windows.Forms.CheckBox otpCheckBox;
        private System.Windows.Forms.TextBox otpTextBox;
        private System.Windows.Forms.Label regionLabel;
        private System.Windows.Forms.ComboBox regionComboBox;
        private System.Windows.Forms.CheckBox pcRegCheckBox;
        private System.Windows.Forms.TextBox MacAddressTextBox;
        private System.Windows.Forms.CheckBox gameMode32BitCheckBox;
        private System.Windows.Forms.CheckBox rememberDataCheckBox;
        private System.Windows.Forms.CheckBox loginAutomaticallyCheckBox;
        private System.Windows.Forms.CheckBox launcherUpdateCheckBox;
        private System.Windows.Forms.CheckBox gameUpdateCheckBox;
        private System.Windows.Forms.Button startGameBtn;
        private System.Windows.Forms.CheckBox adminCheckBox;
        private System.Windows.Forms.LinkLabel githubLinkLabel;
        private System.Windows.Forms.LinkLabel gameDirectoryPathLinkLabel;
    }
}

