namespace Launcher.Forms
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up used resources.
        /// </summary>
        /// <param name="disposing">True if managed resources are to be deleted; otherwise, False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Windows Form Designer

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.LoginGroupBox = new System.Windows.Forms.GroupBox();
            this.adminCheckBox = new System.Windows.Forms.CheckBox();
            this.MacAddressTextBox = new System.Windows.Forms.TextBox();
            this.MacAddressCheckBox = new System.Windows.Forms.CheckBox();
            this.UsernameTextBox = new System.Windows.Forms.TextBox();
            this.UsernameLabel = new System.Windows.Forms.Label();
            this.PasswordLabel = new System.Windows.Forms.Label();
            this.PasswordTextBox = new System.Windows.Forms.TextBox();
            this.OtpCheckBox = new System.Windows.Forms.CheckBox();
            this.OtpTextBox = new System.Windows.Forms.TextBox();
            this.RegionLabel = new System.Windows.Forms.Label();
            this.RegionComboBox = new System.Windows.Forms.ComboBox();
            this.GameMode32BitCheckBox = new System.Windows.Forms.CheckBox();
            this.RememberDataCheckBox = new System.Windows.Forms.CheckBox();
            this.LoginAutomaticallyCheckBox = new System.Windows.Forms.CheckBox();
            this.launcherUpdateCheckBox = new System.Windows.Forms.CheckBox();
            this.gameUpdateCheckBox = new System.Windows.Forms.CheckBox();
            this.btn_startGame = new System.Windows.Forms.Button();
            this.GameDirectoryPathLinkLabel = new System.Windows.Forms.LinkLabel();
            this.GithubLinkLabel = new System.Windows.Forms.LinkLabel();
            this.LoginGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // LoginGroupBox
            // 
            this.LoginGroupBox.Controls.Add(this.adminCheckBox);
            this.LoginGroupBox.Controls.Add(this.MacAddressTextBox);
            this.LoginGroupBox.Controls.Add(this.MacAddressCheckBox);
            this.LoginGroupBox.Controls.Add(this.UsernameTextBox);
            this.LoginGroupBox.Controls.Add(this.UsernameLabel);
            this.LoginGroupBox.Controls.Add(this.PasswordLabel);
            this.LoginGroupBox.Controls.Add(this.PasswordTextBox);
            this.LoginGroupBox.Controls.Add(this.OtpCheckBox);
            this.LoginGroupBox.Controls.Add(this.OtpTextBox);
            this.LoginGroupBox.Controls.Add(this.RegionLabel);
            this.LoginGroupBox.Controls.Add(this.RegionComboBox);
            this.LoginGroupBox.Controls.Add(this.GameMode32BitCheckBox);
            this.LoginGroupBox.Controls.Add(this.RememberDataCheckBox);
            this.LoginGroupBox.Controls.Add(this.LoginAutomaticallyCheckBox);
            this.LoginGroupBox.Controls.Add(this.launcherUpdateCheckBox);
            this.LoginGroupBox.Controls.Add(this.gameUpdateCheckBox);
            this.LoginGroupBox.Controls.Add(this.btn_startGame);
            this.LoginGroupBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LoginGroupBox.Location = new System.Drawing.Point(12, 12);
            this.LoginGroupBox.Name = "LoginGroupBox";
            this.LoginGroupBox.Size = new System.Drawing.Size(337, 219);
            this.LoginGroupBox.TabIndex = 1;
            this.LoginGroupBox.TabStop = false;
            this.LoginGroupBox.Text = "Login";
            // 
            // adminCheckBox
            // 
            this.adminCheckBox.Location = new System.Drawing.Point(16, 189);
            this.adminCheckBox.Name = "adminCheckBox";
            this.adminCheckBox.Size = new System.Drawing.Size(141, 24);
            this.adminCheckBox.TabIndex = 0;
            this.adminCheckBox.Text = "Launch As Admin";
            this.adminCheckBox.CheckedChanged += new System.EventHandler(this.adminCheckBox_CheckedChanged);
            // 
            // MacAddressTextBox
            // 
            this.MacAddressTextBox.Location = new System.Drawing.Point(129, 107);
            this.MacAddressTextBox.Name = "MacAddressTextBox";
            this.MacAddressTextBox.Size = new System.Drawing.Size(190, 22);
            this.MacAddressTextBox.TabIndex = 15;
            // 
            // MacAddressCheckBox
            // 
            this.MacAddressCheckBox.Location = new System.Drawing.Point(16, 105);
            this.MacAddressCheckBox.Name = "MacAddressCheckBox";
            this.MacAddressCheckBox.Size = new System.Drawing.Size(107, 24);
            this.MacAddressCheckBox.TabIndex = 14;
            this.MacAddressCheckBox.Text = "PC Registration";
            this.MacAddressCheckBox.UseVisualStyleBackColor = true;
            this.MacAddressCheckBox.CheckedChanged += new System.EventHandler(this.MacAddressCheckBox_CheckedChanged);
            // 
            // UsernameTextBox
            // 
            this.UsernameTextBox.Location = new System.Drawing.Point(83, 21);
            this.UsernameTextBox.Name = "UsernameTextBox";
            this.UsernameTextBox.Size = new System.Drawing.Size(236, 22);
            this.UsernameTextBox.TabIndex = 1;
            // 
            // UsernameLabel
            // 
            this.UsernameLabel.AutoSize = true;
            this.UsernameLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UsernameLabel.Location = new System.Drawing.Point(16, 24);
            this.UsernameLabel.Name = "UsernameLabel";
            this.UsernameLabel.Size = new System.Drawing.Size(58, 13);
            this.UsernameLabel.TabIndex = 0;
            this.UsernameLabel.Text = "Username";
            // 
            // PasswordLabel
            // 
            this.PasswordLabel.AutoSize = true;
            this.PasswordLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PasswordLabel.Location = new System.Drawing.Point(16, 52);
            this.PasswordLabel.Name = "PasswordLabel";
            this.PasswordLabel.Size = new System.Drawing.Size(56, 13);
            this.PasswordLabel.TabIndex = 2;
            this.PasswordLabel.Text = "Password";
            // 
            // PasswordTextBox
            // 
            this.PasswordTextBox.Location = new System.Drawing.Point(83, 49);
            this.PasswordTextBox.Name = "PasswordTextBox";
            this.PasswordTextBox.PasswordChar = '*';
            this.PasswordTextBox.Size = new System.Drawing.Size(236, 22);
            this.PasswordTextBox.TabIndex = 3;
            // 
            // OtpCheckBox
            // 
            this.OtpCheckBox.Location = new System.Drawing.Point(16, 79);
            this.OtpCheckBox.Name = "OtpCheckBox";
            this.OtpCheckBox.Size = new System.Drawing.Size(56, 17);
            this.OtpCheckBox.TabIndex = 4;
            this.OtpCheckBox.Text = "OTP";
            this.OtpCheckBox.UseVisualStyleBackColor = true;
            this.OtpCheckBox.CheckedChanged += new System.EventHandler(this.OtpCheckBox_CheckedChanged);
            // 
            // OtpTextBox
            // 
            this.OtpTextBox.Location = new System.Drawing.Point(83, 77);
            this.OtpTextBox.Name = "OtpTextBox";
            this.OtpTextBox.PasswordChar = '*';
            this.OtpTextBox.Size = new System.Drawing.Size(107, 22);
            this.OtpTextBox.TabIndex = 5;
            // 
            // RegionLabel
            // 
            this.RegionLabel.Location = new System.Drawing.Point(193, 80);
            this.RegionLabel.Name = "RegionLabel";
            this.RegionLabel.Size = new System.Drawing.Size(48, 21);
            this.RegionLabel.TabIndex = 6;
            this.RegionLabel.Text = "Region";
            // 
            // RegionComboBox
            // 
            this.RegionComboBox.AutoCompleteCustomSource.AddRange(new string[] { "NA", "EU" });
            this.RegionComboBox.FormattingEnabled = true;
            this.RegionComboBox.Items.AddRange(new object[] { "NA", "EU" });
            this.RegionComboBox.Location = new System.Drawing.Point(247, 77);
            this.RegionComboBox.MaxDropDownItems = 2;
            this.RegionComboBox.Name = "RegionComboBox";
            this.RegionComboBox.Size = new System.Drawing.Size(71, 21);
            this.RegionComboBox.TabIndex = 7;
            this.RegionComboBox.SelectedIndexChanged += new System.EventHandler(this.RegionComboBox_SelectedIndexChanged);
            // 
            // GameMode32BitCheckBox
            // 
            this.GameMode32BitCheckBox.Location = new System.Drawing.Point(16, 135);
            this.GameMode32BitCheckBox.Name = "GameMode32BitCheckBox";
            this.GameMode32BitCheckBox.Size = new System.Drawing.Size(56, 24);
            this.GameMode32BitCheckBox.TabIndex = 8;
            this.GameMode32BitCheckBox.Text = "32 BIT";
            this.GameMode32BitCheckBox.UseVisualStyleBackColor = true;
            this.GameMode32BitCheckBox.CheckedChanged += new System.EventHandler(this.GameModeCheckBox_CheckedChanged);
            // 
            // RememberDataCheckBox
            // 
            this.RememberDataCheckBox.AutoSize = true;
            this.RememberDataCheckBox.Location = new System.Drawing.Point(83, 139);
            this.RememberDataCheckBox.Name = "RememberDataCheckBox";
            this.RememberDataCheckBox.Size = new System.Drawing.Size(107, 17);
            this.RememberDataCheckBox.TabIndex = 9;
            this.RememberDataCheckBox.Text = "Remember Data";
            this.RememberDataCheckBox.UseVisualStyleBackColor = true;
            this.RememberDataCheckBox.CheckedChanged += new System.EventHandler(this.RememberDataCheckBox_CheckedChanged);
            // 
            // LoginAutomaticallyCheckBox
            // 
            this.LoginAutomaticallyCheckBox.AutoSize = true;
            this.LoginAutomaticallyCheckBox.Location = new System.Drawing.Point(193, 139);
            this.LoginAutomaticallyCheckBox.Name = "LoginAutomaticallyCheckBox";
            this.LoginAutomaticallyCheckBox.Size = new System.Drawing.Size(126, 17);
            this.LoginAutomaticallyCheckBox.TabIndex = 10;
            this.LoginAutomaticallyCheckBox.Text = "Login automatically";
            this.LoginAutomaticallyCheckBox.UseVisualStyleBackColor = true;
            this.LoginAutomaticallyCheckBox.CheckedChanged += new System.EventHandler(this.LoginAutomaticallyCheckBox_CheckedChanged);
            // 
            // launcherUpdateCheckBox
            // 
            this.launcherUpdateCheckBox.Location = new System.Drawing.Point(16, 162);
            this.launcherUpdateCheckBox.Name = "launcherUpdateCheckBox";
            this.launcherUpdateCheckBox.Size = new System.Drawing.Size(152, 24);
            this.launcherUpdateCheckBox.TabIndex = 12;
            this.launcherUpdateCheckBox.Text = "Check Launcher Update";
            this.launcherUpdateCheckBox.UseVisualStyleBackColor = true;
            this.launcherUpdateCheckBox.CheckedChanged += new System.EventHandler(this.launcherUpdate_CheckedChanged);
            // 
            // gameUpdateCheckBox
            // 
            this.gameUpdateCheckBox.Location = new System.Drawing.Point(193, 162);
            this.gameUpdateCheckBox.Name = "gameUpdateCheckBox";
            this.gameUpdateCheckBox.Size = new System.Drawing.Size(130, 24);
            this.gameUpdateCheckBox.TabIndex = 13;
            this.gameUpdateCheckBox.Text = "Check Game Update";
            this.gameUpdateCheckBox.UseVisualStyleBackColor = true;
            this.gameUpdateCheckBox.CheckedChanged += new System.EventHandler(this.gameUpdateCheckBox_CheckedChanged);
            // 
            // btn_startGame
            // 
            this.btn_startGame.Location = new System.Drawing.Point(163, 189);
            this.btn_startGame.Name = "btn_startGame";
            this.btn_startGame.Size = new System.Drawing.Size(155, 23);
            this.btn_startGame.TabIndex = 11;
            this.btn_startGame.Text = "Start Game";
            this.btn_startGame.UseVisualStyleBackColor = true;
            this.btn_startGame.Click += new System.EventHandler(this.StartGameButton_Click);
            // 
            // GameDirectoryPathLinkLabel
            // 
            this.GameDirectoryPathLinkLabel.AutoSize = true;
            this.GameDirectoryPathLinkLabel.Location = new System.Drawing.Point(12, 234);
            this.GameDirectoryPathLinkLabel.Name = "GameDirectoryPathLinkLabel";
            this.GameDirectoryPathLinkLabel.Size = new System.Drawing.Size(81, 13);
            this.GameDirectoryPathLinkLabel.TabIndex = 12;
            this.GameDirectoryPathLinkLabel.TabStop = true;
            this.GameDirectoryPathLinkLabel.Text = "Set Game Path";
            this.GameDirectoryPathLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.GameDirectoryPathLinkLabel_LinkClicked);
            // 
            // GithubLinkLabel
            // 
            this.GithubLinkLabel.AutoSize = true;
            this.GithubLinkLabel.Location = new System.Drawing.Point(209, 234);
            this.GithubLinkLabel.Name = "GithubLinkLabel";
            this.GithubLinkLabel.Size = new System.Drawing.Size(140, 13);
            this.GithubLinkLabel.TabIndex = 13;
            this.GithubLinkLabel.TabStop = true;
            this.GithubLinkLabel.Text = "Report An Issue (Click Me)";
            this.GithubLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.GithubLinkLabel_LinkClicked);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(364, 256);
            this.Controls.Add(this.GameDirectoryPathLinkLabel);
            this.Controls.Add(this.GithubLinkLabel);
            this.Controls.Add(this.LoginGroupBox);
            this.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MainForm";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.LoginGroupBox.ResumeLayout(false);
            this.LoginGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.GroupBox LoginGroupBox;
        private System.Windows.Forms.Label UsernameLabel;
        private System.Windows.Forms.TextBox UsernameTextBox;
        private System.Windows.Forms.Label PasswordLabel;
        private System.Windows.Forms.TextBox PasswordTextBox;
        private System.Windows.Forms.CheckBox OtpCheckBox;
        private System.Windows.Forms.TextBox OtpTextBox;
        private System.Windows.Forms.Label RegionLabel;
        private System.Windows.Forms.ComboBox RegionComboBox;
        private System.Windows.Forms.CheckBox MacAddressCheckBox;
        private System.Windows.Forms.TextBox MacAddressTextBox;
        private System.Windows.Forms.CheckBox GameMode32BitCheckBox;
        private System.Windows.Forms.CheckBox RememberDataCheckBox;
        private System.Windows.Forms.CheckBox LoginAutomaticallyCheckBox;
        private System.Windows.Forms.CheckBox launcherUpdateCheckBox;
        private System.Windows.Forms.CheckBox gameUpdateCheckBox;
        private System.Windows.Forms.Button btn_startGame;
        private System.Windows.Forms.CheckBox adminCheckBox;
        private System.Windows.Forms.LinkLabel GithubLinkLabel;
        private System.Windows.Forms.LinkLabel GameDirectoryPathLinkLabel;
    }
}

